---
- name: install server
  hosts: local
  become: true
  connection: local
  gather_facts: false

  tasks:
    - name: upgrade all packages
      yum: update_cache=yes name=* state=latest

    - name: disable selinux [1/2]
      selinux:
        policy: targeted
        state: permissive
    - name: disable selinux [2/2]
      shell: "setenforce 0"

    - name: disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: false
        
    - name: get playbooks
      copy: 
        src: playbooks
        dest: /etc/ansible/
        
    - name: get createsmbuser script
      copy: 
        src: createsmbuser
        dest: /usr/local/bin/
        mode: 0777
        
    - name: get api binary binaries 
      get_url: 
        url: "https://github.com/rh363/apiansible/releases/download/v1.1/apiansible"
        dest: /usr/local/bin/
        mode: 0777
    
    - name: get service
      copy: 
        src: apiansible.service
        dest: /etc/systemd/system/apiansible.service
    
    - name: start service
      service:
        name: apiansible
        state: restarted
        enabled: true


    
