---
- name: add smb server access
  hosts: local
  become: true
  connection: local
  gather_facts: false

  tasks:
    - name: add users
      shell: "createsmbuser {{item.user}} {{item.pass}}"
      loop: "{{ users }}"
    
    - name: restart smb nmb
      service:
        name: "{{ item }}" 
        enabled: yes
        state: restarted
      loop:
        - smb
        - nmb
