---
- name: install smb server
  hosts: local
  become: true
  connection: local
  gather_facts: false

  tasks:
    - name: upgrade all packages
      yum: update_cache=yes name=* state=latest

    - name: install samba package
      yum: name={{ item }} state=latest
      loop:
        - samba 
        - samba-common 
        - samba-client
        - nfs-util
    
    - name: Create a mountable directory if it does not exist
      file:
        path: /sharing
        state: directory
        owner: root
        group: root
        mode: '0775'

    - name: Mount k3s volume
      mount:
        src: "{{ src }}:/exports"
        path: /sharing
        opts: "rw,sync,hard,intr"
        boot: false
        state: mounted
        fstype: nfs

    - name: add smb_group
      group:
        name: smb_group
        gid: 1005
        state: present

    - name: Creating smb configuration file
      copy:
        dest: "/etc/samba/smb.conf"
        content: |
          [global]
          workgroup = {{ workgroup }}
          server string = Samba Server 
          security = user
          dns proxy = no
          log file = /var/log/samba/log.%m
          max log size = 1000
          logging = file
          panic action = /usr/share/samba/panic-action %d
          map to guest = bad user
          [sharing]
          valid users = @smb_group
          path = /sharing
          browsable = yes
          writable = yes
          guest ok = no
          read only = no
    
    - name: restart smb and nmb
      service:
        name: "{{ item }}" 
        enabled: yes
        state: restarted
      loop:
        - smbd
        - nmbd
    
