---
- name: remove nfs server access
  hosts: local
  become: true
  connection: local
  gather_facts: false
  
  tasks:
   
    - name: remove exports configuration lines
      lineinfile:
        path: /etc/exports
        regexp: "{{ item }}"
        state: absent
      loop: "{{ dests }}"

    
    - name: restart rpcbind and nfs-server
      service:
        name: "{{ item }}" 
        enabled: yes
        state: restarted
      loop:
        - rpcbind
        - nfs-server


    