---
- name: uninstall smb server
  hosts: local
  become: true
  connection: local
  gather_facts: false

  tasks:

    - name: get user
      shell: "getent passwd | awk -F: '$4 == 1005 {print $1}'"
      register: users

    - name: remove all users
      user:
        name: "{{ item }}"
        state: absent
        remove: yes
      loop: "{{ users.stdout_lines }}"
    
    - name: remove group
      group: 
        name: smb_group
        state: absent
     
    - name: remove samba package
      yum: name={{ item }} state=absent
      loop:
        - samba 
        - samba-common 
        - samba-client
        - nfs-utils

    - name: Umount k3s volume if already exists
      mount:
        path: /sharing
        state: unmounted
        
    - name: Remove mountable directory if it exists
      file:
        path: /sharing
        state: absent
        
    - name: Remove samba config directory
      file:
        path: /etc/samba
        state: absent
        
